#请不要修改此值
config-version: '4'


config:
  # 语言: english / spanish / chinese
  lang: chinese


  # 模式: tripwire / item_frame
  # 此设置需要重启服务器
  # ------------ tripwire ------------
  # 优势:
  #      ● 几乎完全异步
  #      ● 有原版一样的真实碰撞体积
  #
  # 劣势:
  #      ● 拌线数量限制（127）
  #      ● 破坏拌线产生的视觉问题
  #      ● 无法移除破坏拌线的音效
  #
  # ------------ item_frame ------------
  # 优势:
  #      ● 无限制农作物数量
  #      ● 支持旋转
  #
  # 劣势:
  #      ● 展示框是实体，相对较卡
  #      ● Spigot优化了实体可见距离
  #      ● 没有真实的碰撞体积
  #      ● ItemsAdder的战利品系统无法应用于家具
  #
  crop-mode: tripwire



  # 农作物会有随机的朝向吗?
  # 这只在展示框模式中生效
  rotation:
    enable: false
    # 4 / 8
    variant: 4



  integration:
    #领地保护
    Residence: false
    WorldGuard: false
    Kingdoms: false
    GriefDefender: false
    PlotSquared: false
    Towny: false
    Lands: false
    GriefPrevention: false
    CrashClaim: false
    #增加技能经验
    AureliumSkills: false
    mcMMO: false
    MMOCore: false
    EcoSkills: false
    #季节同步
    RealisticSeasons: false



  # Mode 1:
  #      ● 农作物仅在加载中的区块生长
  # Mode 2:
  #      ● 在线玩家种植的农作物会生长
  # Mode 3:
  #      ● （推荐） Mode 1 + Mode 2
  # Mode 4:
  #      ● 在这个模式下请关闭季节
  #      ● 所有数据内的农作物都会生长
  grow-mode: 3
  # 开始生长的时间(ticks)
  # 1000ticks 代表游戏时间 7点 (0-23999)
  # 洒水器将在所有农作物完成生长后开始工作
  grow-time:
    - 1000
  # 农作物将在开始生长的时间点后多少秒内完成生长（seconds）
  # 这是为了避免大量农作物在同一时间点进行判断和方块替换，否则会造成卡顿
  # 假如你有100个农作物，默认配置代表在游戏时间7点后的现实时间60秒内，100个农作物会在这60秒内随机时间点完成生长
  time-to-grow: 60
  # 和上面的配置类似，只不过这一次是洒水器工作的时间
  time-to-work: 30
  # 异步时间检测 (需要重启)
  # 服务端可能因为某些原因跳tick，所以异步模式下可能会错过生长判断
  # 异步检测不是很有必要，同步的检测也不会造成性能问题，除非你设置了几百个白名单世界
  async-time-check: false
  # 哪些世界的农作物能够生长（即白名单世界）
  whitelist-worlds:
    - world
  # 所有世界的农作物都生长吗?
  # 此选项适用于单玩家单世界服务器.
  # 这种模式下你只能填写一个白名单世界作为时间，季节的判断依据.
  all-world-grow: false
  # 农作物巨大化是否仅进行一次尝试
  # 如果你喜欢星露谷模式，农作物将在成熟后继续吸收水分，每天都有概率巨大化
  # 如果你喜欢起源模式，你可以设置巨大化农作物为金农作物，并且仅有一次成为金农作物的机会
  gigantic-only-one-try: false



  quality:
    # 如果禁用品质系统，你需要在ItemsAdder的配置文件中单独设置每个农作物的掉落物
    enable: true
    # 默认品质比例
    default-ratio: 17/2/1



  # 使用水桶右键洒水器能够补充几格水量
  sprinkler-refill: 2
  # 使用水壶右键水方块的时候能够为水壶补充多少水量
  water-can-refill: 1
  # 能否使用水壶为洒水器加水
  water-can-add-water-to-sprinkler: true
  # 使用水壶的时候发送水花粒子效果吗
  water-particles: true



  # 是否启用骨粉特性
  bone-meal:
    enable: true
    chance: 0.5
    success-particle: VILLAGER_HAPPY



  # 区块限制最大农作物和洒水器数量
  # 建议开启限制，因为一个区块内过多的农作物方块会导致IA插件报错Stack Overflow
  limit:
    enable: true
    crop: 64
    sprinkler: 8



  # 玩家是否可以使用右键收获农作物
  # 如果禁用右键收获，那么重复收获的特性也会被关闭
  right-click-harvest: true
  # 玩家是否必须要空手才能右键收获
  harvest-with-empty-hand: true
  # 是否阻止玩家在错误季节的种植
  prevent-plant-if-wrong-season: true
  # 是否告知玩家这是错误的季节
  should-notify-if-wrong-season: true